# -*- coding: utf-8 -*-
"""Create_sent_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kVwPg-o2wjtRpYiJUlEnR4ppMful0RC4
"""

import pandas as pd
import numpy as np
import spacy
import os

nlp = spacy.load('en_core_web_sm')

para_data = pd.read_csv("wikipedia_edited_data.csv")
para_data.head()

print(para_data.size)

texts = para_data['text'].to_numpy().tolist()
docs = []
for text in texts:
  doc = nlp(text)
  docs.append(doc)
  del doc
para_data['doc'] = docs

para_data.head()

data_df = {
    "sent": [],
    "category": [],
    "plant": [],
    "genus": [],
    "species": [],
    "plant_group": [],
    "category_int": [],
}

for row in para_data.index:
    text = para_data["text"][row]
    category = para_data["category"][row]
    plant = para_data["plant"][row]
    genus = para_data["genus"][row]
    species = para_data["species"][row]
    plant_group = para_data["plant_group"][row]
    category_int = para_data["category_int"][row]
    doc = para_data["doc"][row]
    for sent in doc.sents:
        data_df["sent"].append(sent.text)
        data_df["category"].append(category)
        data_df["plant"].append(plant)
        data_df["genus"].append(genus)
        data_df["species"].append(species)
        data_df["plant_group"].append(plant_group)
        data_df["category_int"].append(category_int)

sent_data = pd.DataFrame(data_df)

sent_data.head()

print(sent_data.size)

sent_data.to_csv('wikipedia_edited_data_sents.csv')

